### ISSUE TITLE
As a user, I want to update my profile

### ISSUE THREAD

**Issue by trezy** [RollForGuild/rollforguild.com#56]
## Prerequisites

- [X] RollForGuild/TheGM#19

## Acceptance Criteria

- [x] I can change my bio

- [x] I can change my password
- [x] I can change and crop my avatar

## Removed Criteria
- ~I can change my email~ moved to new issue (tobemade)
- ~I can add or remove games that I have played~ Moved #74
- ~I can add or remove games that I want to play~ Moved #74
- ~I receive a notification to check my new email address for confirmation.~ no longer relevent/needed

**Comment by UncleClapton** [comment]
I can add a manage page while I'm at it with the profile view

**Comment by trezy** [comment]
@UncleClapton That would be fantastic. Just make sure to do them as separate PRs to represent the separated cards. 😉

**Comment by UncleClapton** [comment]
Can do
